# Generated by Django 3.2.7 on 2021-09-27 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_register_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(default='Mathematics', on_delete=django.db.models.deletion.CASCADE, to='account.course')),
            ],
        ),
    ]
