# Generated by Django 3.2.7 on 2021-09-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_register_status'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50)),
                ('lesson_no', models.IntegerField()),
                ('video', models.FileField(upload_to='videos')),
                ('ppt', models.FileField(upload_to='ppt')),
                ('notes', models.FileField(upload_to='notes')),
                ('course', models.ForeignKey(default='Mathematics', on_delete=django.db.models.deletion.CASCADE, to='account.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
        ),
    ]
