# Generated by Django 3.2.7 on 2021-09-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_subject_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user',
        ),
    ]
