# Generated by Django 3.2.7 on 2021-09-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_alter_lessons_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.subject'),
        ),
    ]
