# Generated by Django 3.2.6 on 2021-12-15 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_lab_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_cycle',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
