# Generated by Django 3.2.7 on 2021-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_register_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
