# Generated by Django 3.2.7 on 2021-09-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_register_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='register',
            name='course',
            field=models.ForeignKey(default='Mathematics', on_delete=django.db.models.deletion.CASCADE, to='account.course'),
        ),
    ]
