# Generated by Django 3.2.7 on 2021-09-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210925_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_active',
        ),
    ]
