# Generated by Django 3.2.7 on 2021-09-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_register_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
