# Generated by Django 3.2.6 on 2021-12-01 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_announcement_complaints_placement_suggestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='dat',
            new_name='date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='complaints',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
