# Generated by Django 3.2.7 on 2021-10-03 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='program',
            name='mark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
