# Generated by Django 3.2.6 on 2021-12-15 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_lab_cycle_due_date'),
        ('student', '0002_auto_20211003_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='lab_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.lab_cycle'),
        ),
    ]
