# Generated by Django 3.2.6 on 2021-12-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_program_lab_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='due',
            field=models.BooleanField(default=False),
        ),
    ]
